dspace-group/dscom

- .editorconfig
- src/dscom/TypeProvider.cs
- src/dscom/writer/ElemDescBasedWriter.cs
- src/dscom/writer/MethodWriter.cs
- src/dscom/writer/ParameterWriter.cs
- src/dscom/writer/StructWriter.cs
Write MarshalAs error in ReportEvent
> Write MarshalAs error in ReportEvent

- src/dscom.client/TypeLibConverterOptions.cs
- src/dscom/TypeLibConverter.cs
- src/dscom/TypeLibConverterSettings.cs
- src/dscom/WriterContext.cs
Moved all options to a CLI specific options class.
> Settings and options moved

- src/dscom.client/Program.cs
- src/dscom/TypeLibConverter.cs
- src/dscom/TypeLibExporter.cs
* Check platform type 
* write error to StdError
* typo in options fixed
> Check platform and write error to StdError

- src/dscom/writer/ClassWriter.cs
Ignore unresolved ComVisible interface. UseCase: Framework interface without TLB.
> Ignore unresolved interface

- src/dscom/dscom.csproj
Enhancement: Usage of .NET SourceLink #52
> Added .NET SourceLink dependency to dscom project

- src/dscom.client/Program.cs
- src/dscom.client/TypeLibConverterOptions.cs
- src/dscom.client/TypeLibExporterNotifySink.cs
- src/dscom.test/builder/DynamicAssemblyBuilder.cs
- src/dscom.test/tests/CLITest/CLITest.cs
- src/dscom.test/tests/CLITest/CompileReleaseFixture.cs
- src/dscom/TypeLibConverterSettings.cs
Added the new parameter which allows you to prevent a recursive call of dscom. 
#51
> New parameter: createmissingdependenttlbs

- dscom.sln
- src/dscom.demo/assembly3/IDemoInterfaceComInvisible.cs
- src/dscom.demo/assembly3/System.Net.Http.cs
- src/dscom.demo/assembly3/assembly3.csproj
- src/dscom.test/tests/CLITest/CLITest.cs
- src/dscom.test/tests/CLITest/CompileReleaseFixture.cs
- src/dscom/TypeInfoResolver.cs
- src/dscom/writer/ElemDescBasedWriter.cs
Added a bugfix for #56 where the overrideTlbId was not used to resolved references.
> Dev/56 overridetlbid leads to errors and warnings during type resolution 

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- global.json
> Global Config update

- src/dscom.client/Program.cs
- src/dscom.client/dscom.client.csproj
- src/dscom.test/dscom.test.csproj
- src/dscom.test/tests/CLITest/CLITest.cs
- src/dscom/dscom.csproj
> Update package references

- .github/dependabot.yml
- src/dscom.client/dscom.client.csproj
- src/dscom.test/dscom.test.csproj
- src/dscom/dscom.csproj
> build: Updated packages

- scripts/demo32Bit.bat
- src/dscom.demo/assembly1/DemoStruct.cs
- src/dscom/TypeProvider.cs
> fix: Use VT_I4 for IntPtr in case of 32-bit

- .github/workflows/build.yaml
- .github/workflows/release.yaml
> build: Update to actions/checkout@v3

- src/dscom.client/Program.cs
- src/dscom.test/tests/CLITest/CLITest.cs
> fix: registers and unregister with exact path instead of relative path

- src/dscom/RegistrationServices.cs
This PR fixes to issues.
1. Dismiss (de-)registration of generic types, as Marshal cannot generate a ProgId for these types
2. Fix Registry Handling due to permission errors
> Fixing Faulting De-Registration

- README.md
> doc: Update MsBuild Description

- README.md
- src/dscom.build/TlbExport.cs
- src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Task.targets
- src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets
- src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.props
- src/dscom.client/Program.cs
- src/dscom/TypeLibConverterSettings.cs
- src/dscom/writer/LibraryWriter.cs
> feat: Added an override for the auto-generated library name

- .github/workflows/code-style.yaml
- .github/workflows/example-test.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-test.yaml
- global.json
Set version explicit to `>=6.0.4.06`
```
{
"sdk": {
"version": "6.0.406",
"rollForward": "latestPatch"
}
```
> build: global.json added

- dscom.sln
- src/dscom.demo/assembly5/ExplodeyBaseClass.cs
- src/dscom.demo/assembly5/ExplodeyMember.cs
- src/dscom.demo/assembly5/ExplodeyParameter.cs
- src/dscom.demo/assembly5/IExportableType.cs
- src/dscom.demo/assembly5/Properties/AssemblyInfo.cs
- src/dscom.demo/assembly5/assembly5.csproj
- src/dscom/AssemblyExtensions.cs
- src/dscom/MethodBaseExtensions.cs
- src/dscom/TypeExtensions.cs
- src/dscom/names/ComAliasNameResolver.cs
- src/dscom/writer/LibraryWriter.cs
Closes #204 by turning an exception into a warning
> Match `ReflectionTypeLoadException` handling from `LibraryWriter` into `ComAliasNameResolver`

- src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets
> fix: Added spaces between build task arguments

- README.md
> docs: Add Limitation for DsComTypeLibraryEmbedAfterBuild

- src/dscom.test/tests/PropertyTest.cs
- src/dscom/writer/PropertySetMethodWriter.cs
Hello,
here is the requested pull request for the given issue.
closed #306 
Best regards
Patrick
> Property Setter do not use INVOKEKIND.INVOKE_PROPERTYPUTREF

- src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.targets
> Set the default values. If the override is set, use it instead

- src/dscom.test/builder/DynamicMethodBuilder.cs
- src/dscom.test/builder/DynamicParameterBuilder.cs
- src/dscom.test/builder/DynamicPropertyBuilder.cs
- src/dscom.test/tests/MemIdTest.cs
- src/dscom.test/tests/MethodTests.cs
- src/dscom.test/tests/NamesTest.cs
- src/dscom/DispatchIdCreator.cs
Hello,
in this Pull Request i improved the convention, that property named 'value' have the DispId(0) by Default.
That is only the case, if there are no index-parameters.
Greetings
> DispId(0) for Value-Property

- src/dscom/TypeInfoResolver.cs
> Don't check that referenced TLB is named the same as DLL it was created from

- src/dscom.test/dscom.test.csproj
[https://github.com/fluentassertions/fluentassertions/pull/2943](https://github.com/fluentassertions/fluentassertions/pull/2943)
> chore: Pinned FluentAssertions version
