src/dscom.demo/assembly1/IDemoInterfaceWithMarshalAs.cs
src/dscom.test/TypeLibExporterNotifySink.cs
src/dscom.test/builder/DynamicAssemblyBuilder.cs
src/dscom.test/builder/DynamicAssemblyBuilderResult.cs
src/dscom.test/tests/MarshalAsTest.cs
src/dscom/writer/ParameterWriter.cs

- Fixed various typos in the code and comments 
- Added a special handling that Parameters with MarshalAs attribute don't create a warning 
- Sorted the demo class 
- Extended the demo class to reproduce the problem from #50

fix: Bugfix/50 warning regarding type substitution

---

src/dscom/RegistrationServices.cs

Fixes #98 
Uses the GUID of the assembly as a fallback for registration if the type does not have a GUID attribute.

fix: 98 registertypeforcomclients fails when type does not have a guidattribute

---

src/dscom/RegistrationServices.cs

In .NET FullFramework the `RegistrationServices` class provided both - a `RegisterAssembly` and an `UnregisterAssembly` method.
Based on the original implementation, this pull requests adds a reimplementation of the registration und deregistration functionality for dscom.
Limitations:
- InProc Registration only will take place, if a [comhost](https://learn.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com) assembly is present.
- No CustomRegisterFunction Or CustomUnRegisterFunction Attribute support
- No PrimaryInteropAssembly Support
Reviewer:

feat: Added the ability to register and unregister an entire assembly for COM

---

README.md
src/dscom.build/TlbExport.cs
src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Task.targets
src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets
src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.props

In #131 names were introduced in form of an alias. The names parameter was already supported before
but ignored by the MsBuild tasks.
This will add the names to the MsBuild tasks

fix: Add Names to MsBuild Tasks

---

src/dscom/RegistrationServices.cs

In #133 there are two different issues with the component registration.
The first issue is regarding the NEUTRAL_LOCALE which is always created, even if another value exists. This can now be opted-in.
The second issue is regarding the missing elevation. According to the merged view of ClassesRoot, a user space COM registration can be performed as well. Hence a permission check is applied to check at which registry part the registration should be applied to.
Closes #133

fix: Component Registration and Locales

---

src/dscom.build/dscom.build.csproj

microsoft.build.tasks.core will be loaded at tun-time by MsBuild dspace.runtime.interopservices will be loaded at run-time by the build task
No need to add these recursive dependencies.
Closes "Too many files in output directory" #141

fix: Drop Dependencies recursive

---

src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets

If the output path contains whitespace, these will be taken into account.
Closes "Build fails, when project path contains whitespaces" #148

fix: Whitespace in AssemblyPath

---

.github/workflows/release.yaml

select the .NET version which is used while publishing a new release

fix: ensure that the correct .NET version is used

---

src/dscom/TypeInfoResolver.cs
src/dscom/writer/MethodWriter.cs
src/dscom/writer/PropertyMethodWriter.cs

This change can improve performance for large assemblies/type libraries by a factor of 2 or more (>100 in extreme cases).
Added caches for:
- TypeInfoResolver.ResolveTypeInfo(Type)
- MethodWriter.IsComVisible
- PropertyMethodWriter.IsComVisible

perf: Improve performance by introducing caches to hotspots

---

src/dscom/writer/ElemDescBasedWriter.cs
src/dscom/writer/EnumWriter.cs
src/dscom/writer/MethodWriter.cs
src/dscom/writer/ParameterWriter.cs
src/dscom/writer/TypeWriter.cs

Warning messages now contain the names of the relevant types and members. This makes analysis of a warning easier.

Show type and member names in warning messages

---

src/dscom.demo/assembly3/IDemoInterfaceComInvisible.cs
src/dscom/writer/PropertyMethodWriter.cs

If an interface contains multiple indexers, but only one is ComVisible = true, dscom throws an unexpected exception "Ambiguous match found".
This is because dscom searched for the indexer property via its special name "get_Item". However, if multiple indexers exist this throws an exception.
Instead of searching for the propery by name we search by its getter or setter methods.

fix: "ambiguous match" error when exporting multiple indexers

---

src/dscom.client/AssemblyResolver.cs

fix: #207 Set isCollectible to false in the AssemblyLoadContext creation 
This will make the AssemblyLoadContext impossible to unload during the runtime of the client and should allow C++ CLI assemblies to be loaded. 
resolves #207

fix: unloadable app context

---

src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets

Exec WorkingDirectory should be `$(OutDir)` as default and `$(OutputPath)` as fallback.
`$(OutputPath)` might not work on large complex solutions.
See https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/Tasks/Microsoft.Common.CurrentVersion.targets#L107-L122
_'OutDir and OutputPath are distinguished for legacy reasons, and OutDir should be used if at all possible.'_
Experienced this error in my solution where `$(OutDir)` is used.
```
Calling dscom.exe to export type library
P:\code\packages_installed\dspace.runtime.interopservices.buildtasks\1.7.0\build\dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets(64,5): error MSB6003: The specified task executable "cmd.exe" could not be run. System.IO.DirectoryNotFoundException: The working directory …
```

fix: Changed WorkingDirectory to $(OutDir) as default and $(OutputPath) as fallback

---

src/dscom.demo/assembly5/ExplodeyBaseClass.cs
src/dscom/writer/LibraryWriter.cs

fix: #259 Exception on trying to load namespace attribute 
Moved the check for the namespace attribute after the check for COM visibility, because classes and libraries which are `ComVisible = false` will be skipped and should not receive further checks.

259 error could not load file or assembly presentationframework on tlbexport regression in 160

---

README.md
src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets
src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.targets

Fix for [#289](https://github.com/dspace-group/dscom/issues/289)
Add overridable properties for _DsComExportTypeLibraryTargetFile and _DsComExportTypeLibraryAssemblyFile

Added CLI based task overridable properties

---

.github/dependabot.yml

Not only NuGet Packages deprecate

ci: Update github-actions regularly

---

src/dscom/TypeInfoResolver.cs
src/dscom/writer/LibraryWriter.cs

Closes #310 
I'm not sure if this is the best way to fix this.
It feels like `TypeLibExporterNotifySink.ResolveRef` is a better location. However, it does not have access to `_additionalLibs` in `TypeInfoResolver`.

Demand-load tlbs instead of always loading them

---

src/dscom.client/AssemblyResolver.cs
src/dscom.client/Program.cs
src/dscom/RegisterAssemblySettings.cs
src/dscom/RegistrationServices.cs

Hello,
I have the problem that I have a .NET 8.0 assembly that I need to register as COM to make it available for VB6 (for Debugging). So far, I have used dscom32.exe for this purpose, both to create and register the TLB.
With regsvr32.exe, I encounter an issue where the application does not work with my assembly because there are classes that implement a generic interface. However, these interfaces are not COM-visible and are only necessary for internal wrapping.
To address this, I created the command 'asmregister', which is intended to handle the tasks of regasm.exe.
This Pull-Request is more like a Proposal for implementing this.
Furthermore i got the problem, that after this procedure i can't run the VB6 Application, because there is a mismatch in the interface. I think that VB6 can …

feat: Support for regasm.exe functionalities

---

src/dscom/TypeInfoResolver.cs

fix: Match TLBs to assemblies according to their file name, case insensitive

---

src/dscom.test/BaseTest.cs
src/dscom.test/builder/DynamicAssemblyBuilder.cs
src/dscom.test/tests/MarshalAsTest.cs
src/dscom.test/tests/MemIdTest.cs

The writing of temporary dll and tlb files has been removed.  
In the case of parallel execution of the UnitTest, this is not stable and sporadically generates errors. 
In addition, a large number of files are generated that are neither used for test execution nor do they provide any advantage.
The test execution time can thus be massively accelerated.

test: Removed tlb and dll writing for demo and analysis

---

.github/workflows/code-style.yaml
src/dscom.test/Extensions.cs
src/dscom.test/GlobalSuppressions.cs
src/dscom.test/GlobalUsing.cs
src/dscom.test/dscom.test.csproj
src/dscom.test/tests/AttributeFlagTests.cs
src/dscom.test/tests/CLITest/CLITest.cs
src/dscom.test/tests/CLITest/CLITestBase.cs
src/dscom.test/tests/CLITest/CLITestEmbed.cs
src/dscom.test/tests/ClassTest.cs
src/dscom.test/tests/ComVisibilityTest.cs
src/dscom.test/tests/DefaultInterfaceTest.cs
src/dscom.test/tests/EnumTest.cs
src/dscom.test/tests/EventTests.cs
src/dscom.test/tests/InterfaceTest.cs
src/dscom.test/tests/MarshalAsTest.cs
src/dscom.test/tests/MemIdTest.cs
src/dscom.test/tests/MethodTests.cs
src/dscom.test/tests/NamesTest.cs
src/dscom.test/tests/PropertyTest.cs
src/dscom.test/tests/RegistrationServicesTest.cs
src/dscom.test/tests/StructTest.cs
src/dscom.test/tests/TypeLibTest.cs

[https://github.com/fluentassertions/fluentassertions/pull/2943](https://github.com/fluentassertions/fluentassertions/pull/2943)
Fluent assertions has changed its license model.  
See video from Nick: [https://www.youtube.com/watch?v=ZFc6jcaM6Ms&t=2s](https://www.youtube.com/watch?v=ZFc6jcaM6Ms&t=2s)
Fluent assertions is just a **nice to have** library.  
All functions can also be replaced by the classic `Xunit.Assert`. This is not fluent but who cares.  
I would not recommend any company to use FluentAssertions and then pay 130$ per developer for it.  
If you had never had a library like fluentassertions before, nobody would have thought of paying 130$ for it.  
I understand it when it comes to a library where there is still a lot of development work to be done.   
But the …

test: FluentAssertions removed

---

src/dscom/TypeProvider.cs

We are currently replacing tlbexp with dscom and faced an incompatibility that should be fixed with this pull request. Consider following COM interface:
[
Guid("XXX-Y-Y-Y-ZZZZZ"),
ComVisible(true)
]
public interface IMethodsWithPointers
{
unsafe void TheMethod(uint pixelInLine, ushort* pInput);
};
tlbexp renders it to TLB as
[...]
interface IMethodsWithPointers : IUnknown {
HRESULT _stdcall TheMethod([in] unsigned long pixelInLine, [in, out] unsigned short* pInput);
};
dscom delivers following TLB definition:
[...]
interface IMethodsWithPointers : IUnknown {
HRESULT _stdcall TheMethod([in] unsigned long pixelInLine, [in] IUnknown* pInput);
};
Obviously dscom doesn't process C# pointer types properly, this has to be adressed by my change.

add support for pointer types for method parameter

---

src/dscom.client/Program.cs

Hi,
I was trying to tlbexport a Winforms UserControl and I was struggling with an error about System.Drawing.Common missing.
After I while I noticed that it was really a consequence of the --asmpath I typed that wasn't correctly identified. (i.e. --asmpath "C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.18\" is not correctly identified, it should be --asmpath "C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.18")
I added a simple Directory.Exists check that would have saved me quite some time!
PS: as changes are in dscom.client probject only, I didn't include any test as there was no test project for the console app. Just tell me if you require them.

fix: Validate not existing or badly formed entries in asmpath 
